// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace SharedMemMap
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct DataRow : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static DataRow GetRootAsDataRow(ByteBuffer _bb) { return GetRootAsDataRow(_bb, new DataRow()); }
  public static DataRow GetRootAsDataRow(ByteBuffer _bb, DataRow obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public DataRow __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string RowId { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetRowIdBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetRowIdBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetRowIdArray() { return __p.__vector_as_array<byte>(4); }
  public bool IsActive { get { int o = __p.__offset(6); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public SharedMemMap.NestedDetails? Details(int j) { int o = __p.__offset(8); return o != 0 ? (SharedMemMap.NestedDetails?)(new SharedMemMap.NestedDetails()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int DetailsLength { get { int o = __p.__offset(8); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<SharedMemMap.DataRow> CreateDataRow(FlatBufferBuilder builder,
      StringOffset row_idOffset = default(StringOffset),
      bool is_active = false,
      VectorOffset detailsOffset = default(VectorOffset)) {
    builder.StartTable(3);
    DataRow.AddDetails(builder, detailsOffset);
    DataRow.AddRowId(builder, row_idOffset);
    DataRow.AddIsActive(builder, is_active);
    return DataRow.EndDataRow(builder);
  }

  public static void StartDataRow(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddRowId(FlatBufferBuilder builder, StringOffset rowIdOffset) { builder.AddOffset(0, rowIdOffset.Value, 0); }
  public static void AddIsActive(FlatBufferBuilder builder, bool isActive) { builder.AddBool(1, isActive, false); }
  public static void AddDetails(FlatBufferBuilder builder, VectorOffset detailsOffset) { builder.AddOffset(2, detailsOffset.Value, 0); }
  public static VectorOffset CreateDetailsVector(FlatBufferBuilder builder, Offset<SharedMemMap.NestedDetails>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateDetailsVectorBlock(FlatBufferBuilder builder, Offset<SharedMemMap.NestedDetails>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateDetailsVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<SharedMemMap.NestedDetails>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateDetailsVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<SharedMemMap.NestedDetails>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartDetailsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<SharedMemMap.DataRow> EndDataRow(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SharedMemMap.DataRow>(o);
  }
}


static public class DataRowVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyString(tablePos, 4 /*RowId*/, false)
      && verifier.VerifyField(tablePos, 6 /*IsActive*/, 1 /*bool*/, 1, false)
      && verifier.VerifyVectorOfTables(tablePos, 8 /*Details*/, SharedMemMap.NestedDetailsVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
