// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace SharedMemMap
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct NestedDetails : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static NestedDetails GetRootAsNestedDetails(ByteBuffer _bb) { return GetRootAsNestedDetails(_bb, new NestedDetails()); }
  public static NestedDetails GetRootAsNestedDetails(ByteBuffer _bb, NestedDetails obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public NestedDetails __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public double Temperature { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetDouble(o + __p.bb_pos) : (double)0.0; } }
  public double Humidity { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetDouble(o + __p.bb_pos) : (double)0.0; } }
  public int StatusCode { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<SharedMemMap.NestedDetails> CreateNestedDetails(FlatBufferBuilder builder,
      double temperature = 0.0,
      double humidity = 0.0,
      int status_code = 0) {
    builder.StartTable(3);
    NestedDetails.AddHumidity(builder, humidity);
    NestedDetails.AddTemperature(builder, temperature);
    NestedDetails.AddStatusCode(builder, status_code);
    return NestedDetails.EndNestedDetails(builder);
  }

  public static void StartNestedDetails(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddTemperature(FlatBufferBuilder builder, double temperature) { builder.AddDouble(0, temperature, 0.0); }
  public static void AddHumidity(FlatBufferBuilder builder, double humidity) { builder.AddDouble(1, humidity, 0.0); }
  public static void AddStatusCode(FlatBufferBuilder builder, int statusCode) { builder.AddInt(2, statusCode, 0); }
  public static Offset<SharedMemMap.NestedDetails> EndNestedDetails(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SharedMemMap.NestedDetails>(o);
  }
}


static public class NestedDetailsVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Temperature*/, 8 /*double*/, 8, false)
      && verifier.VerifyField(tablePos, 6 /*Humidity*/, 8 /*double*/, 8, false)
      && verifier.VerifyField(tablePos, 8 /*StatusCode*/, 4 /*int*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
